### ISSUE TITLE
作者现在解决了1424*802分辨率的问题，能否解决更多分辨率的bug？

### ISSUE THREAD

**Issue by chengjianhao** [zysuper/rice-cracker#3]
现在在1424*802下，解决了开机花屏和唤醒花屏问题。除了logo放大，都已经完美了。
但是个人感觉这个分辨率不合适，字体有点偏大，之前使用的1680*945这个分辨率，体验还是非常好的，在13版本中也是支持hidpi的。但是在14系统下，如果用老的rdm方法实现这个分辨率，睡眠后会出现闪屏的状况，情况感觉还是很严重的。
作者能否支持一下更多的分辨率，能提供更多的选择。
期待有新的更新。

**Comment by stevezz3** [comment]
@chengjianhao 此脚本只负责休眠后拉伸屏幕，拉伸后的闪屏等bug属于系统显卡驱动层面，脚本修复不了。
